#!/bin/bash

OPTIND=1         # Reset in case getopts has been used previously in the shell.
port=8090
openbrowser=0
run_command=$2
default_command=".build/debug/${PWD##*/}"

function usage() {
	if [ "$1" != "" ] 
	then
		echo "Usage Error: $1"
		echo ""
	fi
	echo "Usage: $0 [-h|-o|-p <port>] {build | install | run <command>}"
	echo "	-h : display options"
	echo "	-p <port> : port to listen on both locally and in container (default=8090)"
	echo "	-o : open browser on localhost:$port"
	echo "	     default <command> is $default_command"
	exit 0
}

#
# Make sure Docker is installed
#
docker version > /dev/null 2> /dev/null
status=$?

if [ "$status" != "0" ]
then
	echo "Install docker on this machine to use this script."
	sys=`uname -s`
	dockerurl=https://docs.docker.com/engine/installation/
	if [ "$sys" == "Darwin" ]
	then
		dockerurl=https://docs.docker.com/docker-for-mac/
	fi
	echo "Go to $dockerurl for more instructions."
	open $dockerurl
	exit
fi

#
# Common way to run docker with passed in command to run
#
function run_docker() {
	args="$@"
	docker run -e "PORT=$port" --privileged --init --rm -i -t -v `pwd`:/root/app -w "/root/app" -p $port:$port ibmcom/swift-ubuntu $args
}

while getopts "okhp:" opt; do
    case "$opt" in
    o)  openbrowser=1
        ;;
    p)  port=$OPTARG
        ;;
    h)  usage
        ;;
    esac
done

shift $((OPTIND-1))

if [ "$1" == "install" ]
then
	set -x
	sudo ln -sf `pwd`/dockit /usr/local/bin/dockit
	docker pull ibmcom/swift-ubuntu
	set +x
	exit $?
fi

#onport=`lsof -L -i:$port | grep LISTEN | sed 's/[^ ]* //' | sed 's/^ *//' | sed 's/ .*//'`
onport=`lsof -L -i:$port | grep LISTEN`

# Check that no one is listening on our port
if [ "$onport" != "" ]
then
	echo "Another process already listening on port $port"
	echo "Either stop the following processes or override with the -p <port> option"
	lsof -L -i:$port | grep LISTEN
	exit 1
fi

if [ ! -e "Package.swift" ]
then
	usage "This command must be run in a directory that contains a Swift package"
fi

if [ $openbrowser -eq 1 ] 
then
	open http://localhost:$port
fi

# if no command passed in, default to ./build/debug/<dirname>
if [ "$command" == "" ]
then
	command=$default_command
fi

case "$1" in
build)
	echo "Building on Linux"
	run_docker swift build
	;;
run)
	if [ -f "./$command" ]
	then
		echo "Running $2 on Linux"
		echo "  Note: Local port $port is mapping to port $port in container"
		echo "	      Use -o option to open a browser session to this port or open manually"
		run_docker $command
	else
		usage "<command> must point to a command within relative directory (default: $default_command)"
	fi
	;;
debug)
	if [ -f "./$command" ]
	then
		echo "Debugging $2 on Linux"
		run_docker lldb $command
	else
		usage "<command> must point to a command within relative directory (default: $default_command)"
	fi
	;;
*)
	usage
esac
